// import Vue from "vue";
// import "../components/Highlight";
// import "../components/LineChart";
// import "../components/DonutChart";
// import "../components/BarChart";
// import "../components/PieChart";
// import "../components/GoogleMapLoader";
// import "../components/LitePicker";
// import "../components/Tippy";
// import "../components/TippyContent";
// import "../components/TailSelect";
// import "../components/LoadingIcon";
//
// Vue.component("Highlight", () => import("../components/Highlight"));
// Vue.component("LineChart", () => import("../components/LineChart"));
// Vue.component("DonutChart", () => import("../components/DonutChart"));
// Vue.component("BarChart", () => import("../components/BarChart"));
// Vue.component("PieChart", () => import("../components/PieChart"));
// Vue.component("GoogleMapLoader", () => import("../components/GoogleMapLoader"));
// Vue.component("LitePicker", () => import("../components/LitePicker"));
// Vue.component("Tippy", () => import("../components/Tippy"));
// Vue.component("TippyContent", () => import("../components/TippyContent"));
// Vue.component("TailSelect", () => import("../components/TailSelect"));
// Vue.component("LoadingIcon", () => import("../components/LoadingIcon"));
